Added Client Certificate Authentication support
ibm-watson-iot/iot-java pull request #100
Opened 2017-07-11 11:37 UTC by amprasanna

2017-07-11 11:43 UTC, sathipal reviewed
1. Use logs instead of System outs.
2. Elaborate more on why the new version of the Paho MQTT is required
3. Update the relevant document about the certificate support.

2017-07-12 09:13 UTC, CaroMac requested changes
For line 32, should be Watson IoT Platform, not Platform.

2017-07-12 09:16 UTC, CaroMac requested changes
Suggest the Key additions paragraph be slightly amended to - Version 0.2.5 of the Watson IoT Java Client Library extends the authentication mechanism by adding support for Client side Certificate based authentication. The enhanced security policies enable organizations to determine how they want devices to connect to and be authenticated to the platform. The extended security options that are available to an organization depend on the plan type. Lite, Standard or Advanced Security Plan (ASP) types are available.

2017-07-26 07:39 UTC, sathipal approved these changes

2017-07-26 07:39 UTC, merged